# Generated by Django 2.0.5 on 2018-06-08 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myguestbook', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='guestbook',
            name='avatar',
            field=models.CharField(default='https://avatar.csdn.net/3/9/5/3_lenny_lin.jpg', max_length=200),
        ),
        migrations.AlterField(
            model_name='guestbook',
            name='email',
            field=models.EmailField(max_length=200),
        ),
        migrations.AlterField(
            model_name='guestbook',
            name='weburl',
            field=models.URLField(),
        ),
    ]
